<a href="https://colab.research.google.com/github/loonita/Data-science/blob/main/Notebook_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [2]:
import pandas as pd
import numpy as np

In [3]:
variable = 1+2
print (variable)

3


In [4]:
arreglo = np.zeros(12)
print(arreglo)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
arreglo1 = [0] * 10
arreglo2 = arreglo1
arreglo2[4] = 10 # posicion 5 = indice 4

print(arreglo2)

[0, 0, 0, 0, 10, 0, 0, 0, 0, 0]


In [8]:
#listas
arreglo = list(range(10, 50))
print(arreglo)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


In [9]:
#crear lista
arreglo_ej_4 = np.arange(0, 9)
arreglo = np.array(arreglo_ej_4)
arreglo_2d = arreglo.reshape(3, 3)

print(arreglo_2d)
print(type(arreglo_2d))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
<class 'numpy.ndarray'>


In [11]:
arreglo = np.random.random(100)
print('arreglo de numeros aleatorios', arreglo)

arreglo de numeros aleatorios [9.28397155e-01 7.31510355e-01 5.32072296e-01 9.08059056e-01
 6.46175643e-01 9.71710846e-01 5.24417007e-01 8.88581022e-01
 4.11552170e-01 4.18721610e-01 5.21418978e-01 4.01323209e-01
 8.46335674e-01 1.08118265e-01 2.91886971e-01 4.48237415e-01
 8.74129788e-01 1.42601068e-01 3.41989969e-01 1.04387061e-01
 9.57887844e-01 2.40341513e-01 9.29539510e-01 4.42477282e-01
 1.68123343e-01 7.36699271e-01 1.53505195e-01 3.83050888e-01
 3.62474946e-01 6.38128105e-01 8.41651060e-01 8.60959724e-01
 6.43997574e-01 1.91884757e-01 2.85038123e-01 7.43252288e-01
 3.48598427e-01 3.28940285e-01 2.48746573e-01 3.31793449e-01
 1.10378463e-01 6.05636974e-01 4.14321547e-01 5.33135429e-01
 3.95023705e-01 6.81195564e-01 2.65021959e-02 9.25022410e-01
 4.36087068e-01 1.78882550e-01 2.93241660e-01 2.06507290e-01
 7.67718455e-01 3.13619888e-01 8.36312886e-02 7.30796835e-01
 6.53132240e-01 5.30996695e-01 1.53026384e-01 2.52126878e-01
 5.06624464e-01 7.06639029e-01 9.99563789e-01 2.3722005

In [13]:
arreglo = np.random.random(100)
suma = np.sum(arreglo)
tamano = np.size(arreglo)
media = suma / tamano

print ('media del arreglo', media)

media del arreglo 0.5319880210133491


In [ ]:

arreglo = np.random.random